# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:4002']

  - job_name: 'website-service'
    static_configs:
      - targets: ['website-service:4003']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:4004']